### ISSUE TITLE
Documentation compilation fails on docs.rs

### ISSUE THREAD

**Issue by elinorbgr** [PolyMeilex/libseat-rs#1]
https://docs.rs/crate/libseat/0.1.1/builds/399159

Looks like the `custom_logger` features (on by default) fails because it cannot find the `#include <libseat.h>` include for compiling `log_handler.c`, maybe the feature needs to be disabled for docs.rs build ?

For reference: https://docs.rs/about/metadata

**Comment by PolyMeilex** [comment]
Indeed, my bad. Thanks!

**Comment by PolyMeilex** [comment]
Version 1.0.3 should now build correctly https://docs.rs/libseat/0.1.3 (don't ask me what heaped to 0.1.2 that's an embarasing story)
