### ISSUE TITLE
Remove slog or make it optional

### ISSUE THREAD

**Issue by chrisduerr** [PolyMeilex/libseat-rs#3]
The latest Smithay removed `slog` in favor of `tracing`. However slog is still in Smithay's dependency tree due to libseat's dependency on it.

I personally have never used logging in libseat, so I'm not sure if I'd mind its complete removal, but at the very least it should probably be put behind a feature flag. The most sensible solution is likely a migration to tracing.

**Comment by PolyMeilex** [comment]
I think I will just move to regular log and call it a day.

Logging adapter to c library is already optional (`custom_logger` feature), but slog is not, as it was part of public API.

**Comment by PolyMeilex** [comment]
This was done in latest release.
